services:
  - type: web
    name: deepfake-detector
    runtime: docker
    repo: https://github.com/EtimbukUdofia/Deepfake-Image-Detector
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: 5000
